name: Publish to Pub.dev

on:
  pull_request:
    branches: [ master ]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: 'Flutter Package'
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          skipTests: true
